package com.marioprieto.barcodereader;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.graphics.Bitmap;
import android.graphics.drawable.BitmapDrawable;
import android.graphics.drawable.Drawable;
import android.net.Uri;
import android.os.Bundle;
import android.provider.MediaStore;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.MultiFormatWriter;
import com.google.zxing.WriterException;
import com.google.zxing.common.BitMatrix;
import com.journeyapps.barcodescanner.BarcodeEncoder;

import java.io.File;


public class QRGenerated extends AppCompatActivity {

    ImageView imageView;
    Button save;
    Button share;
    Drawable drawable;
    Uri URI;
    Bitmap bitmap;
    String ImagePath;
    String textoguardado;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_qrgenerated);
        imageView = (ImageView) findViewById(R.id.qr);
        save = (Button) findViewById(R.id.save);
        share = (Button) findViewById(R.id.share);

        Bundle bundle2 = this.getIntent().getExtras();
        String texto = bundle2.getString("texto");
        MultiFormatWriter multiFormatWriter = new MultiFormatWriter();
        textoguardado = texto;
        try {
            BitMatrix bitMatrix = multiFormatWriter.encode(textoguardado, BarcodeFormat.QR_CODE,500,500);
            BarcodeEncoder barcodeEncoder = new BarcodeEncoder();
            Bitmap bitmap = barcodeEncoder.createBitmap(bitMatrix);
            imageView.setImageBitmap(bitmap);

        } catch (WriterException e) {
            e.printStackTrace();
        }

        save.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                saveQR(true);
            }
        });

        share.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                shareQR();
            }
        });
    }

    @SuppressLint("ResourceType")
    public void saveQR(Boolean flag){
        drawable = ((BitmapDrawable)imageView.getDrawable());
        bitmap = ((BitmapDrawable)drawable).getBitmap();
        ImagePath = MediaStore.Images.Media.insertImage(
                getContentResolver(),
                bitmap,
                textoguardado,
                "QR Generated by BarcodeReader <marioprieto.com>"
        );
        URI = Uri.parse(ImagePath);
        if(flag){
            Toast.makeText(QRGenerated.this, "Imagen guardada correctamente.", Toast.LENGTH_LONG).show();
        } else {

        }
    }

    public void shareQR() {
        saveQR(false);
        Intent share = new Intent(Intent.ACTION_SEND);
        share.setType("image/png");
        share.putExtra(Intent.EXTRA_STREAM, URI);
        startActivity(Intent.createChooser(share,"Compartir mediante"));
    }
}